// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_GITHUB_ID: string;
	BETTER_AUTH_GITHUB_SECRET: string;
	DB: D1Database;
}
