/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as staticIndexRouteImport } from './routes/(static)/index'
import { Route as staticPathRouteImport } from './routes/(static)/path'
import { Route as staticCharactersRouteImport } from './routes/(static)/characters'
import { Route as staticPlaygroundRouteRouteImport } from './routes/(static)/playground/route'
import { Route as dashboardDashboardRouteRouteImport } from './routes/(dashboard)/dashboard/route'
import { Route as dashboardAuthRouteRouteImport } from './routes/(dashboard)/auth/route'
import { Route as staticPlaygroundIndexRouteImport } from './routes/(static)/playground/index'
import { Route as dashboardDashboardIndexRouteImport } from './routes/(dashboard)/dashboard/index'
import { Route as dashboardAuthIndexRouteImport } from './routes/(dashboard)/auth/index'
import { Route as staticResourcesFilenameRouteImport } from './routes/(static)/resources/$filename'
import { Route as staticResourcesSplatRouteImport } from './routes/(static)/resources/$'
import { Route as dashboardDashboardSettingsIndexRouteImport } from './routes/(dashboard)/dashboard/settings/index'
import { Route as dashboardDashboardRequestIndexRouteImport } from './routes/(dashboard)/dashboard/request/index'
import { Route as dashboardApiAuthSplatRouteImport } from './routes/(dashboard)/api/auth/$'
import { Route as dashboardApiImageIdFilenameRouteImport } from './routes/(dashboard)/api/image/$id/$filename'

const staticIndexRoute = staticIndexRouteImport.update({
  id: '/(static)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const staticPathRoute = staticPathRouteImport.update({
  id: '/(static)/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const staticCharactersRoute = staticCharactersRouteImport.update({
  id: '/(static)/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const staticPlaygroundRouteRoute = staticPlaygroundRouteRouteImport.update({
  id: '/(static)/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRouteRoute = dashboardDashboardRouteRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAuthRouteRoute = dashboardAuthRouteRouteImport.update({
  id: '/(dashboard)/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const staticPlaygroundIndexRoute = staticPlaygroundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => staticPlaygroundRouteRoute,
} as any)
const dashboardDashboardIndexRoute = dashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardDashboardRouteRoute,
} as any)
const dashboardAuthIndexRoute = dashboardAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardAuthRouteRoute,
} as any)
const staticResourcesFilenameRoute = staticResourcesFilenameRouteImport.update({
  id: '/(static)/resources/$filename',
  path: '/resources/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const staticResourcesSplatRoute = staticResourcesSplatRouteImport.update({
  id: '/(static)/resources/$',
  path: '/resources/$',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardSettingsIndexRoute =
  dashboardDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => dashboardDashboardRouteRoute,
  } as any)
const dashboardDashboardRequestIndexRoute =
  dashboardDashboardRequestIndexRouteImport.update({
    id: '/request/',
    path: '/request/',
    getParentRoute: () => dashboardDashboardRouteRoute,
  } as any)
const dashboardApiAuthSplatRoute = dashboardApiAuthSplatRouteImport.update({
  id: '/(dashboard)/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardApiImageIdFilenameRoute =
  dashboardApiImageIdFilenameRouteImport.update({
    id: '/(dashboard)/api/image/$id/$filename',
    path: '/api/image/$id/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof dashboardAuthRouteRouteWithChildren
  '/dashboard': typeof dashboardDashboardRouteRouteWithChildren
  '/playground': typeof staticPlaygroundRouteRouteWithChildren
  '/characters': typeof staticCharactersRoute
  '/path': typeof staticPathRoute
  '/': typeof staticIndexRoute
  '/resources/$': typeof staticResourcesSplatRoute
  '/resources/$filename': typeof staticResourcesFilenameRoute
  '/auth/': typeof dashboardAuthIndexRoute
  '/dashboard/': typeof dashboardDashboardIndexRoute
  '/playground/': typeof staticPlaygroundIndexRoute
  '/api/auth/$': typeof dashboardApiAuthSplatRoute
  '/dashboard/request/': typeof dashboardDashboardRequestIndexRoute
  '/dashboard/settings/': typeof dashboardDashboardSettingsIndexRoute
  '/api/image/$id/$filename': typeof dashboardApiImageIdFilenameRoute
}
export interface FileRoutesByTo {
  '/characters': typeof staticCharactersRoute
  '/path': typeof staticPathRoute
  '/': typeof staticIndexRoute
  '/resources/$': typeof staticResourcesSplatRoute
  '/resources/$filename': typeof staticResourcesFilenameRoute
  '/auth': typeof dashboardAuthIndexRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
  '/playground': typeof staticPlaygroundIndexRoute
  '/api/auth/$': typeof dashboardApiAuthSplatRoute
  '/dashboard/request': typeof dashboardDashboardRequestIndexRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsIndexRoute
  '/api/image/$id/$filename': typeof dashboardApiImageIdFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)/auth': typeof dashboardAuthRouteRouteWithChildren
  '/(dashboard)/dashboard': typeof dashboardDashboardRouteRouteWithChildren
  '/(static)/playground': typeof staticPlaygroundRouteRouteWithChildren
  '/(static)/characters': typeof staticCharactersRoute
  '/(static)/path': typeof staticPathRoute
  '/(static)/': typeof staticIndexRoute
  '/(static)/resources/$': typeof staticResourcesSplatRoute
  '/(static)/resources/$filename': typeof staticResourcesFilenameRoute
  '/(dashboard)/auth/': typeof dashboardAuthIndexRoute
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
  '/(static)/playground/': typeof staticPlaygroundIndexRoute
  '/(dashboard)/api/auth/$': typeof dashboardApiAuthSplatRoute
  '/(dashboard)/dashboard/request/': typeof dashboardDashboardRequestIndexRoute
  '/(dashboard)/dashboard/settings/': typeof dashboardDashboardSettingsIndexRoute
  '/(dashboard)/api/image/$id/$filename': typeof dashboardApiImageIdFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/playground'
    | '/characters'
    | '/path'
    | '/'
    | '/resources/$'
    | '/resources/$filename'
    | '/auth/'
    | '/dashboard/'
    | '/playground/'
    | '/api/auth/$'
    | '/dashboard/request/'
    | '/dashboard/settings/'
    | '/api/image/$id/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/characters'
    | '/path'
    | '/'
    | '/resources/$'
    | '/resources/$filename'
    | '/auth'
    | '/dashboard'
    | '/playground'
    | '/api/auth/$'
    | '/dashboard/request'
    | '/dashboard/settings'
    | '/api/image/$id/$filename'
  id:
    | '__root__'
    | '/(dashboard)/auth'
    | '/(dashboard)/dashboard'
    | '/(static)/playground'
    | '/(static)/characters'
    | '/(static)/path'
    | '/(static)/'
    | '/(static)/resources/$'
    | '/(static)/resources/$filename'
    | '/(dashboard)/auth/'
    | '/(dashboard)/dashboard/'
    | '/(static)/playground/'
    | '/(dashboard)/api/auth/$'
    | '/(dashboard)/dashboard/request/'
    | '/(dashboard)/dashboard/settings/'
    | '/(dashboard)/api/image/$id/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardAuthRouteRoute: typeof dashboardAuthRouteRouteWithChildren
  dashboardDashboardRouteRoute: typeof dashboardDashboardRouteRouteWithChildren
  staticPlaygroundRouteRoute: typeof staticPlaygroundRouteRouteWithChildren
  staticCharactersRoute: typeof staticCharactersRoute
  staticPathRoute: typeof staticPathRoute
  staticIndexRoute: typeof staticIndexRoute
  staticResourcesSplatRoute: typeof staticResourcesSplatRoute
  staticResourcesFilenameRoute: typeof staticResourcesFilenameRoute
  dashboardApiAuthSplatRoute: typeof dashboardApiAuthSplatRoute
  dashboardApiImageIdFilenameRoute: typeof dashboardApiImageIdFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(static)/': {
      id: '/(static)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof staticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/path': {
      id: '/(static)/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof staticPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/characters': {
      id: '/(static)/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof staticCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/playground': {
      id: '/(static)/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof staticPlaygroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/auth': {
      id: '/(dashboard)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof dashboardAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/playground/': {
      id: '/(static)/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof staticPlaygroundIndexRouteImport
      parentRoute: typeof staticPlaygroundRouteRoute
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexRouteImport
      parentRoute: typeof dashboardDashboardRouteRoute
    }
    '/(dashboard)/auth/': {
      id: '/(dashboard)/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof dashboardAuthIndexRouteImport
      parentRoute: typeof dashboardAuthRouteRoute
    }
    '/(static)/resources/$filename': {
      id: '/(static)/resources/$filename'
      path: '/resources/$filename'
      fullPath: '/resources/$filename'
      preLoaderRoute: typeof staticResourcesFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/resources/$': {
      id: '/(static)/resources/$'
      path: '/resources/$'
      fullPath: '/resources/$'
      preLoaderRoute: typeof staticResourcesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/settings/': {
      id: '/(dashboard)/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof dashboardDashboardSettingsIndexRouteImport
      parentRoute: typeof dashboardDashboardRouteRoute
    }
    '/(dashboard)/dashboard/request/': {
      id: '/(dashboard)/dashboard/request/'
      path: '/request'
      fullPath: '/dashboard/request/'
      preLoaderRoute: typeof dashboardDashboardRequestIndexRouteImport
      parentRoute: typeof dashboardDashboardRouteRoute
    }
    '/(dashboard)/api/auth/$': {
      id: '/(dashboard)/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof dashboardApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/api/image/$id/$filename': {
      id: '/(dashboard)/api/image/$id/$filename'
      path: '/api/image/$id/$filename'
      fullPath: '/api/image/$id/$filename'
      preLoaderRoute: typeof dashboardApiImageIdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface dashboardAuthRouteRouteChildren {
  dashboardAuthIndexRoute: typeof dashboardAuthIndexRoute
}

const dashboardAuthRouteRouteChildren: dashboardAuthRouteRouteChildren = {
  dashboardAuthIndexRoute: dashboardAuthIndexRoute,
}

const dashboardAuthRouteRouteWithChildren =
  dashboardAuthRouteRoute._addFileChildren(dashboardAuthRouteRouteChildren)

interface dashboardDashboardRouteRouteChildren {
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
  dashboardDashboardRequestIndexRoute: typeof dashboardDashboardRequestIndexRoute
  dashboardDashboardSettingsIndexRoute: typeof dashboardDashboardSettingsIndexRoute
}

const dashboardDashboardRouteRouteChildren: dashboardDashboardRouteRouteChildren =
  {
    dashboardDashboardIndexRoute: dashboardDashboardIndexRoute,
    dashboardDashboardRequestIndexRoute: dashboardDashboardRequestIndexRoute,
    dashboardDashboardSettingsIndexRoute: dashboardDashboardSettingsIndexRoute,
  }

const dashboardDashboardRouteRouteWithChildren =
  dashboardDashboardRouteRoute._addFileChildren(
    dashboardDashboardRouteRouteChildren,
  )

interface staticPlaygroundRouteRouteChildren {
  staticPlaygroundIndexRoute: typeof staticPlaygroundIndexRoute
}

const staticPlaygroundRouteRouteChildren: staticPlaygroundRouteRouteChildren = {
  staticPlaygroundIndexRoute: staticPlaygroundIndexRoute,
}

const staticPlaygroundRouteRouteWithChildren =
  staticPlaygroundRouteRoute._addFileChildren(
    staticPlaygroundRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  dashboardAuthRouteRoute: dashboardAuthRouteRouteWithChildren,
  dashboardDashboardRouteRoute: dashboardDashboardRouteRouteWithChildren,
  staticPlaygroundRouteRoute: staticPlaygroundRouteRouteWithChildren,
  staticCharactersRoute: staticCharactersRoute,
  staticPathRoute: staticPathRoute,
  staticIndexRoute: staticIndexRoute,
  staticResourcesSplatRoute: staticResourcesSplatRoute,
  staticResourcesFilenameRoute: staticResourcesFilenameRoute,
  dashboardApiAuthSplatRoute: dashboardApiAuthSplatRoute,
  dashboardApiImageIdFilenameRoute: dashboardApiImageIdFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
